#!/bin/zsh

set -v

cp ~/.qrc/functions/gt .
cp ~/.qrc/scripts/_gt_helper .
cp ~/.qrc/completions/_gt .

sed -i '' 's|/Users/qzhang/.qrc/scripts/_gt_helper|GT_HELPER_ABSPATH|' gt
sed -i '' 's|/Users/qzhang/.qrc/scripts/_gt_helper|GT_HELPER_ABSPATH|' _gt
sed -i '' 's|/Users/qzhang/.gt|GT_ROOTDIR|' _gt
sed -i '' 's|,.wf|    |' _gt_helper
sed -i '' '/\.md/d' _gt_helper
sed -i '' '/Brave/d' _gt_helper

set +v

echo
echo 'For the gt file, also remember to remove all bp, bs resource arrays and parsers,'
echo '   keep the bi arrays but comment out the bi opening line.'
echo
